routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ManajemenBarangController;
use App\Http\Controllers\TransaksiController;
use App\Models\Barang;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data = Barang::all();
    return view('index', ['data' => $data]);
})->name('index');

Route::get('/dashboard', function () {
    return view('dashboard._partials.dashboard');
})->middleware(['auth'])->name('dashboard');

Route::resource('barang', ManajemenBarangController::class)
    ->middleware([
        'auth',
        'can:admin, App\Models\User'
    ]);

Route::get('/transaksi', [TransaksiController::class, 'index'])
    ->middleware(['auth'])
    ->name('transaksi');

Route::get('/transaksi/detail/{user}', [TransaksiController::class, 'detail'])
    ->middleware(['auth', 'can:admin, \App\Models\User'])
    ->name('detail');

Route::post('bayar', [TransaksiController::class, 'bayar'])
    ->middleware(['auth', 'can:user, \App\Models\User'])
    ->name('bayar');

Route::post('beli/{id}', [TransaksiController::class, 'beli'])
    ->name('beli')
    ->middleware([
        'auth',
        'can:user, App\Models\User'
    ]);

Route::post('konfirmasi', [TransaksiController::class, 'konfirmasi'])
    ->name('konfirmasi')
    ->middleware(['auth', 'can:admin, App\Models\User']);

require __DIR__.'/auth.php';

resources/views/dashboard/_partials/dashboard.blade.php
@extends('dashboard.index')
@section('content')
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        </div>

        <!-- Content Row -->
        <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Earnings (Monthly)</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-calendar fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    Earnings (Annual)</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                                </div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                                    </div>
                                    <div class="col">
                                        <div class="progress progress-sm mr-2">
                                            <div class="progress-bar bg-info" role="progressbar"
                                                style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                                aria-valuemax="100"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Pending Requests Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                    Pending Requests</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-comments fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/_partials/editBarang.blade.php
@extends('dashboard.index')
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Manajemen Barang</h1>
    <p class="mb-4">
        Silahkan acak acak, obrak abrik sesuka hati anda
    </p>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tambah Barang</h6>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul style="margin-bottom:0">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('barang.update', $data->id) }}" 
                method="post" 
                enctype="multipart/form-data"
            >
                @method('PUT')
                @csrf
                <div class="form-group">
                    <input type="text" class="form-control"
                        name="nama" id="nama" value="{{ old('nama', $data->nama) }}"
                        placeholder="Masukkan Nama Produk">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" id="harga"
                        name="harga" placeholder="Masukkan Nominal Harga"
                        value="{{ old('harga', $data->harga) }}">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" id="stok"
                        name="stok" placeholder="Masukkan Jumlah Stok"
                        value="{{ old('stok', $data->stok) }}">
                </div>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="gambar"
                        id="customFile" name="gambar">
                    <label class="custom-file-label" for="customFile">
                        {{ $data->foto }}
                    </label>
                </div>
                <div class="mt-4">
                    <button class="btn btn-primary addProduk" type="submit">
                        Edit
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/dashboard/_partials/manajemen_barang.blade.php
@extends('dashboard.index')
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Manajemen Barang</h1>
    <p class="mb-4">
        Silahkan acak acak, obrak abrik sesuka hati anda
    </p>

    @if( session('status') )
        <div class="alert alert-{{ session('alert') }}">
            {{ session('status') }}
        </div>
    @endif

    <!-- Table -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List Barang</h6>
        </div>
        <div class="card-body">
            <a href="{{ route('barang.create') }}" class="btn btn-info btn-icon-split"
                style="margin-bottom:.5em;">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Tambah Data</span>
            </a>
            <div class="table-responsive">
                <table class="table table-bordered" 
                    id="dataTable" width="100%" 
                    cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th>Nama</th>
                            <th>Gambar</th>
                            <th>Harga</th>
                            <th>Stok</th>
                            <th>Modifikasi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($data as $barang)
                            <tr>
                                <td class="text-center">{{ $barang->nama }}</td>
                                <td class="d-flex justify-content-center">
                                    <img width="200" 
                                        src="{{ asset('upload/barang') . '/' . $barang->foto }}" alt="Barang image">
                                </td>
                                <td class="text-center">{{ $barang->harga }}</td>
                                <td class="text-center">{{ $barang->stok }}</td>
                                <td>
                                    <div class="d-flex justify-content-center align-items-center">
                                        <div>
                                            <a class="btn btn-flat btn-primary" 
                                                href="{{ route('barang.edit', $barang->id) }}">
                                                Edit
                                            </a>
                                        </div>
                                        <div>
                                            <form action="{{ route('barang.destroy', $barang->id) }}"
                                                method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button class="btn btn-flat btn-danger"
                                                    type="submit"
                                                    onclick="return confirm('yakin?');">
                                                    Delete
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/_partials/tambahBarang.blade.php
@extends('dashboard.index')
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Manajemen Barang</h1>
    <p class="mb-4">
        Silahkan acak acak, obrak abrik sesuka hati anda
    </p>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tambah Barang</h6>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul style="margin-bottom:0">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('barang.store') }}" 
                method="post" 
                enctype="multipart/form-data"
            >
                @method('POST')
                @csrf
                <div class="form-group">
                    <input type="text" class="form-control"
                        name="nama" id="nama" value="{{ old('nama') }}"
                        placeholder="Masukkan Nama Produk">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" id="harga"
                        name="harga" placeholder="Masukkan Nominal Harga"
                        value="{{ old('harga') }}">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" id="stok"
                        name="stok" placeholder="Masukkan Jumlah Stok"
                        value="{{ old('stok') }}">
                </div>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="gambar"
                        id="customFile" name="gambar">
                    <label class="custom-file-label" for="customFile">
                        Masukkan Gambar Produk
                    </label>
                </div>
                <div class="mt-4">
                    <button class="btn btn-primary addProduk" type="submit">
                        Tambah
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/dashboard/_partials/transaksi.blade.php
@extends('dashboard.index')
@section('content')
    @can('admin', App\Models\User::class)
        @include('dashboard._partials.transaksi_partials.admin')
    @elsecan('user', App\Models\User::class)
        @include('dashboard._partials.transaksi_partials.user')
    @endcan
@endsection